import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="bg-white">
      <head />
      <body className="bg-white min-h-screen">
        <div className="w-full flex justify-center">
          <div className="w-full max-w-7xl">
            <nav className="flex items-center justify-between px-12 pt-8 pb-4 bg-[#1B365D] shadow text-white rounded-t-3xl">
              <div className="flex items-center h-10">
                <Link href="/" className="text-white text-3xl font-bold tracking-tight hover:opacity-80 transition-opacity cursor-pointer" style={{ fontFamily: 'Georgia, Times New Roman, serif', letterSpacing: '0.02em', fontSize: '2.25rem', lineHeight: '2.5rem' }}>J.P.Morgan</Link>
              </div>
              <div className="flex items-center gap-8">
                <Link href="/" className="text-white text-base font-semibold hover:underline">Dashboard</Link>
                <a href="#" className="text-white text-base font-semibold hover:underline">Clients</a>
                <a href="#" className="text-white text-base font-semibold hover:underline">Reports</a>
                <a href="#" className="text-white text-base font-semibold hover:underline">Settings</a>
                <button className="text-white hover:bg-blue-900 rounded-full p-2">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-4.35-4.35m0 0A7.5 7.5 0 104.5 4.5a7.5 7.5 0 0012.15 12.15z" />
                  </svg>
                </button>
              </div>
            </nav>
            <div className="rounded-b-3xl shadow-2xl w-full flex flex-col items-start overflow-hidden">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
